services:
  client:
    stdin_open: true
    container_name: react-br24
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
networks:
  default:
    name: react-br24
